-  name: Backend Setup
   hosts: all
   become: yes
   tasks:
   -  name: Disable default Nodejs version
      ansible.builtin.shell: dnf module disable nodejs -y

   -  name: Enable nodejs module for v20
      ansible.builtin.shell: dnf module enable nodejs:20 -y

   -  name: Install NodeJS
      ansible.builtin.dnf:
        name: nodejs
        state: installed

   - name: Add Application User
     ansible.builtin.user:
       name: expense



   - name: Clean old content
     ansible.builtin.file:
       path: /app
       state: absent

   - name: Create App Directory
     ansible.builtin.file:
       path: /app
       state: directory

   - name: Download and extract the Backend app content
     ansible.builtin.unarchive:
       src: https://expense-artifacts.s3.amazonaws.com/expense-backend-v2.zip
       dest: /app
       remote_src: yes

   - name: Copy Backend service file
     ansible.builtin.file:
       src: backend.service
       dest: /etc/systemd/system/backend.service

   - name: Update packages based on package.json to their latest version.
     community.general.npm:
       path: /app
       state: latest

   - name: Install Mysql Client
     ansible.builtin.dnf:
       name: mysql
       state: installed

   - name: Load Schema
     community.mysql.mysql_db:
       state: import
       name: all
       target: /app/schema/backend.sql

   - name: Start backend service
     ansible.builtin.systemd_service:
       state: restarted
       daemon_reload: true
       name: backend
       enabled: yes



