

- name: get secrets
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3.11
  tasks:
    - name: create a common secret
      ansible.builtin.lineinfile:
        path: ~/secret.json
        line: "{{ lookup('hashi_vault', 'secret=common/data/ssh token={{ vault_token }} url=http://vault.awsdevops.sbs:8200 validate_certs=False') }}"
        create: yes

    - name: create an app secret
      ansible.builtin.lineinfile:
        path: ~/app.json
        line: "{{ lookup('hashi_vault', 'secret=expense-{{ env }}/data/{{ role_name }} token={{ vault_token }} url=http://vault.awsdevops.sbs:8200 validate_certs=False') }}"
        create: yes
