

- name: get secrets
  hosts: localhost
  tasks:
    - name: Force Ansible to use Python 3.9
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/bin/python3.9

    - name: create a common secret
      ansible.builtin.lineinfile:
        path: ~/secret.json
        line: "{{lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=http://vault.awsdevops.sbs:8200 validate_certs=False')}}"
        create: yes