-  name: get secrets
   hosts: localhost
   tasks:
   - name: create a common secret
     ansible.builtin.lineinfile:
       path: ~/secret.json
       line: "{{lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=http://vault.awsdevops.sbs:8200 validate_certs=False')}}"
       create: yes