
#-   name: Get Secrets
#    hosts: localhost
#
#
#    tasks:
#      - name: create a common secret
#        ansible.builtin.lineinfile:
#          path: ~/secret.json
#          line: "{{ lookup('hashi_vault', 'secret=common/data/ssh token=' ~ vault_token ~ ' url=https://vault.awsdevops16297.sbs:8200 validate_certs=False') }}"
#          create: yes
#
#      - name: create an app secret
#        ansible.builtin.lineinfile:
#          path: ~/app.json
#          line: "{{ lookup('hashi_vault', 'secret=expense-' ~ env ~ '/data/' ~ role_name ~ ' token=' ~ vault_token ~ ' url=https://vault.awsdevops16297.sbs:8200 validate_certs=False') }}"
#          create: yes

- name: Get Secrets
  hosts: localhost
  tasks:

    - name: create common secret json
      ansible.builtin.copy:
        dest: ~/secret.json
        content: "{{ lookup('hashi_vault', 'secret=common/data/ssh token=' ~ vault_token ~ ' url=https://vault.awsdevops16297.sbs:8200 validate_certs=False') | to_nice_json }}"

    - name: create app secret json
      ansible.builtin.copy:
        dest: ~/app.json
        content: "{{ lookup('hashi_vault', 'secret=expense-' ~ env ~ '/data/' ~ role_name ~  ' token=' ~ vault_token ~  ' url=https://vault.awsdevops16297.sbs:8200 validate_certs=False') | to_nice_json }}"



