

#- name: get secrets
#  hosts: localhost
#  gather_facts: false
#  vars:
#    ansible_python_interpreter: /usr/bin/python3.9
#  tasks:
#
#    - name: Ensure hvac is installed
#      pip:
#        name: hvac
#        executable: pip3.9
#
#    - name: create a common secret
#      ansible.builtin.lineinfile:
#        path: ~/secret.json
#        line: "{{ lookup('hashi_vault', 'secret=common/data/ssh token={{ vault_token }} url=https://vault.awsdevops.sbs:8200 validate_certs=False') }}"
#        create: yes

-  name: Setup Environment
   hosts: localhost
   gather_facts: false
   tasks:
     - name: Ensure hvac is installed for Ansible Controller (User Space)
       ansible.builtin.pip:
         name: hvac
         extra_args: --user
        # This ensures we target the Python version running Ansible (3.13)
         executable: pip3


-  name: Get Secrets
   hosts: localhost
   tasks:
    - name: create a common secret
      ansible.builtin.lineinfile:
        path: ~/secret.json
        line: "{{ lookup('hashi_vault', 'secret=common/data/ssh token={{ vault_token }} url=https://vault.awsdevops.sbs:8200 validate_certs=False') }}"
        create: yes

    - name: create an app secret
      ansible.builtin.lineinfile:
        path: ~/app.json
        line: "{{ lookup('hashi_vault', 'secret=expense-{{env}}/data/{{role_name}} token={{ vault_token }} url=https://vault.awsdevops.sbs:8200 validate_certs=False') }}"
        create: yes

