
-   name: Get Secrets
    hosts: localhost
    vars:
      vault_url: "https://vault.awsdevops16297.sbs:8200"

    tasks:
      - name: create a common secret
        ansible.builtin.lineinfile:
          path: ~/secret.json
          line: "{{ lookup('hashi_vault', 'secret=common/data/ssh token=' ~ vault_token ~ ' url=https://vault.awsdevops16297.sbs:8200 validate_certs=False') }}"
          create: yes

      - name: create an app secret
        ansible.builtin.lineinfile:
          path: ~/app.json
          line: "{{ lookup('hashi_vault', 'secret=expense-' ~ env ~ '/data/' ~ role_name ~ ' token=' ~ vault_token ~ ' url=https://vault.awsdevops16297.sbs:8200 validate_certs=False') }}"
          create: yes

      - name: Write New Relic key to file
        ansible.builtin.copy:
          dest: ~/newrelic_key.txt
          content: "{{ lookup('hashi_vault', 'secret=expense-' ~ env ~ '/data/' ~ role_name ~ ':NEW_RELIC_KEY token=' ~ vault_token ~ ' url=' ~ vault_url ~ ' validate_certs=False') }}"



