- name: get secrets
  hosts: localhost
  connection: local
  become: yes
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3.13

  tasks:
    - name: Upgrade pip for python3.13
      ansible.builtin.command: >
        /usr/bin/python3.13 -m pip install --upgrade pip
      changed_when: false

    - name: Install hvac using python3.13 pip
      ansible.builtin.command: >
        /usr/bin/python3.13 -m pip install hvac
      changed_when: false

    - name: create a common secret
      ansible.builtin.lineinfile:
        path: ~/secret.json
        line: "{{lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=http://vault.awsdevops.sbs:8200 validate_certs=False')}}"
        create: yes