
-   name: Get Secrets
    hosts: localhost
    vars:
      vault_url: "https://vault.awsdevops16297.sbs:8200"

    tasks:
#      - name: create a common secret
#        ansible.builtin.lineinfile:
#          path: ~/secret.json
#          line: "{{ lookup('hashi_vault', 'secret=common/data/common token=' ~ vault_token ~ ' url=http://vault.awsdevops16297.sbs:8200 validate_certs=False') }}"
#          create: yes
#
#      - name: create an app secret
#        ansible.builtin.lineinfile:
#          path: ~/app.json
#          line: "{{ lookup('hashi_vault', 'secret=expense-' ~ env ~ '/data/' ~ role_name ~ ' token=' ~ vault_token ~ ' url=http://vault.awsdevops16297.sbs:8200 validate_certs=False') }}"
#          create: yes
#
#      - name: Write New Relic key to JSON file
#        ansible.builtin.copy:
#          dest: ~/newrelic_key.json
#          content: |
#            {
#              "NEW_RELIC_KEY": "{{ lookup('hashi_vault', 'secret=expense-' ~ env ~ '/data/' ~ role_name ~ ':NEW_RELIC_KEY token=' ~ vault_token ~ ' url=http://vault.awsdevops16297.sbs:8200 validate_certs=False') }}"
#            }
       - name: Read secrets from Vault
         set_fact:
           vault_secrets: "{{ vault_secrets | default({}) | combine(lookup('hashi_vault', 'secret=' + item + ' token=' + vault_token + ' url=http://vault.awsdevops16297.sbs:8200 validate_certs=False')) }}"
         loop:
           - "common/data/common"
           - "expense-{{env}}/data/{{role_name}}"
           - "rds/data/{{env}}"


       - name: Create secrets.json
         copy:
           dest: ~/secrets.json
           content: "{{ vault_secrets | to_nice_json }}"

