-  name: Mysql setup
   hosts: all
   become: yes
   tasks:
     -  name: Install NodeJS
        ansible.builtin.dnf:
          name: mysql-server
          state: installed

     - name: Install PyMySQL python package
       ansible.builtin.pip:
         name: PyMySQL
         executable: pip3

     -  name: Start mysql server
        ansible.builtin.systemd_service:
          name: mysqld
          enabled: yes
          state: started

     - name: Check the DB connection with our password
       community.mysql.mysql_info:
         login_host: mysql-dev.awsdevops.sbs
         login_user: root
         login_password: ExpenseApp@1
         filter: version

     - name: connect mysql connection
       ansible.builtin.shell: mysql_secure_installation --set-root-pass ExpenseApp@1

#Print_Task_Heading "Connect Mysql server"
#echo 'show databases' | mysql -h mysql-dev.awsdevops.sbs -uroot -p${mysql_password} &>>$Log
#if [ $? -ne 0 ]; then
#mysql_secure_installation --set-root-pass ${mysql_password} &>>$Log
#fi
#check_status $?