- name: Clean old content
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: absent



- name: Create App Directory
  ansible.builtin.file:
    path: "{{ app_loc }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: '0755'

#- name: Download and extract the  app content
#  ansible.builtin.unarchive:
#    src: https://expense-artifacts.s3.amazonaws.com/expense-{{ component }}-v2.zip
#    dest: "{{ app_loc }}"
#    remote_src: yes
#    owner: "{{ app_user }}"
#    group: "{{ app_user }}"

-  name: Download and Extract App Content - From Artifactory
   ansible.builtin.unarchive:
     src: http://{{artifactory_user}}:{{artifactory_password}}@artifactory-internal.awsdevops16297.sbs:8081/artifactory/expense-{{ component }}/{{App_VERSION}}.zip
  #http://{{artifactory_user}}:{{artifactory_password}}@artifactory-internal.rdevops6a.online:8081/artifactory/expense-{{ component }}/{{APP_VERSION}}.zip
     dest: "{{ app_loc }}"
     remote_src: yes
     owner: "{{app_user}}"
     group: "{{app_user}}"