- name: Set prompt with component
  ansible.builtin.shell: set-prompt {{ component }} - {{ env }}

- name: install node_exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter

- name: install Logstash
  ansible.builtin.import_role:
    name: logstash

- name:  rsyslog Configuration
  ansible.builtin.import_role:
    name: rsyslog
  when: rsyslog_config_needed | boolean
