$umask 0022
input {
  file {
    path => "{{ log_file }}"
    #start_position => "beginning"
  }
}

output {
  elasticsearch {
    hosts => "https://elk.awsdevops16297.sbs:9200"
    user => "{{ elastic_user }}"
    password => "{{ elastic_password }}"
    ssl_verification_mode => "none"
    index => "{{ component }}-dev-%{+YYYY.MM.dd}"
  }
  }
